version: "3.9"
services:
  nginx:
    build: ./Front-End
    ports:
      - "5000:443" # Porta 443 do container exposta como 5000 no host
      - "8080:80"
    networks:
      - public
      - internal
    # depends_on:
    #   - api-gateway-1
    #   - api-gateway-2
    restart: always
    volumes:
      - ./Front-End/frontend/dist:/usr/share/nginx/html

  api-gateway-1:
    build: ./API-Gateway
    networks:
      - internal

  api-gateway-2:
    build: ./API-Gateway
    networks:
      - internal

  user-management:
    build: ./User-Management
    networks:
      - internal

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   volumes:
  #     - ./Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - public
  #     - internal

  # nginx-exporter:
  #   image: nginx/nginx-prometheus-exporter:latest
  #   container_name: nginx-exporter
  #   ports:
  #     - 9113:9113
  #   command:
  #     - -nginx.scrape-uri=http://nginx/nginx_status
  #   networks:
  #     - internal
  #   depends_on:
  #     - nginx

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  #     - ./Monitoring/grafana/provisioning:/etc/grafana/provisioning
  #     - ./Monitoring/grafana/dashboards:/var/lib/grafana/dashboards
  #   networks:
  #     - public
  #     - internal
  #   depends_on:
  #     - prometheus

  

volumes:
  grafana-storage:

networks:
  public:
  internal:
